import { Home } from "../components/pages/home/home";

const movieData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/44immBwzhDVyjn87b3x3l9mlhAD.jpg",
      id: 934433,
      title: "Scream VI",
      original_language: "en",
      original_title: "Scream VI",
      overview:
        "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
      poster_path: "/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
      media_type: "movie" as const,
      genre_ids: [27, 9648, 53],
      popularity: 609.941,
      release_date: "2023-03-08",
      video: false,
      vote_average: 7.374,
      vote_count: 684,
    },
    {
      adult: false,
      backdrop_path: "/b9UCfDzwiWw7mIFsIQR9ZJUeh7q.jpg",
      id: 868759,
      title: "Ghosted",
      original_language: "en",
      original_title: "Ghosted",
      overview:
        "Salt-of-the-earth Cole falls head over heels for enigmatic Sadie — but then makes the shocking discovery that she’s a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.",
      poster_path: "/liLN69YgoovHVgmlHJ876PKi5Yi.jpg",
      media_type: "movie" as const,
      genre_ids: [10749, 28, 35],
      popularity: 619.83,
      release_date: "2023-04-21",
      video: false,
      vote_average: 7.318,
      vote_count: 359,
    },
    {
      adult: false,
      backdrop_path: "/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg",
      id: 502356,
      title: "The Super Mario Bros. Movie",
      original_language: "en",
      original_title: "The Super Mario Bros. Movie",
      overview:
        "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
      poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
      media_type: "movie" as const,
      genre_ids: [16, 12, 10751, 14, 35],
      popularity: 7212.464,
      release_date: "2023-04-05",
      video: false,
      vote_average: 7.51,
      vote_count: 1452,
    },
    {
      adult: false,
      backdrop_path: "/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg",
      id: 640146,
      title: "Ant-Man and the Wasp: Quantumania",
      original_language: "en",
      original_title: "Ant-Man and the Wasp: Quantumania",
      overview:
        "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
      poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
      media_type: "movie" as const,
      genre_ids: [28, 12, 878],
      popularity: 9272.643,
      release_date: "2023-02-15",
      video: false,
      vote_average: 6.526,
      vote_count: 1879,
    },
    {
      adult: false,
      backdrop_path: "/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg",
      id: 713704,
      title: "Evil Dead Rise",
      original_language: "en",
      original_title: "Evil Dead Rise",
      overview:
        "Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
      poster_path: "/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
      media_type: "movie" as const,
      genre_ids: [27, 53],
      popularity: 1898.367,
      release_date: "2023-04-12",
      video: false,
      vote_average: 6.965,
      vote_count: 201,
    },
    {
      adult: false,
      backdrop_path: "/fUVK7iUF0k9dU3MwV5MIKWMKGys.jpg",
      id: 298618,
      title: "The Flash",
      original_language: "en",
      original_title: "The Flash",
      overview:
        "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
      poster_path: "/5aZoKcR8VxYWhiENYOUg6ooGbc8.jpg",
      media_type: "movie" as const,
      genre_ids: [878, 28, 12],
      popularity: 170.114,
      release_date: "2023-06-14",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/dQObIWkxfzKEDhtjOSoFnyCVgt0.jpg",
      id: 447365,
      title: "Guardians of the Galaxy Volume 3",
      original_language: "en",
      original_title: "Guardians of the Galaxy Volume 3",
      overview:
        "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
      poster_path: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
      media_type: "movie" as const,
      genre_ids: [878, 12, 28],
      popularity: 235.884,
      release_date: "2023-05-03",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
      id: 76600,
      title: "Avatar: The Way of Water",
      original_language: "en",
      original_title: "Avatar: The Way of Water",
      overview:
        "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
      poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
      media_type: "movie" as const,
      genre_ids: [878, 12, 28],
      popularity: 3471.132,
      release_date: "2022-12-14",
      video: false,
      vote_average: 7.7,
      vote_count: 7530,
    },
    {
      adult: false,
      backdrop_path: "/m0mLjT3TkTXYU2e1XP3wmYDlIml.jpg",
      id: 873256,
      title: "Kiss, Kiss!",
      original_language: "pl",
      original_title: "Gorzko, gorzko!",
      overview:
        "Convinced he can charm any woman, a tenacious flirt sets his sights on a headstrong bride-to-be engaged to the son of an ambitious politician.",
      poster_path: "/jLn0dg0n73v8L6lKkTkX5k8POyy.jpg",
      media_type: "movie" as const,
      genre_ids: [10749, 35],
      popularity: 41.779,
      release_date: "2023-04-26",
      video: false,
      vote_average: 7.25,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/wybmSmviUXxlBmX44gtpow5Y9TB.jpg",
      id: 594767,
      title: "Shazam! Fury of the Gods",
      original_language: "en",
      original_title: "Shazam! Fury of the Gods",
      overview:
        'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
      poster_path: "/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
      media_type: "movie" as const,
      genre_ids: [28, 35, 14],
      popularity: 4319.273,
      release_date: "2023-03-15",
      video: false,
      vote_average: 6.848,
      vote_count: 1215,
    },
    {
      adult: false,
      backdrop_path: "/eSVu1FvGPy86TDo4hQbpuHx55DJ.jpg",
      id: 700391,
      title: "65",
      original_language: "en",
      original_title: "65",
      overview:
        "65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.",
      poster_path: "/rzRb63TldOKdKydCvWJM8B6EkPM.jpg",
      media_type: "movie" as const,
      genre_ids: [878, 12, 53, 28],
      popularity: 1189.997,
      release_date: "2023-03-02",
      video: false,
      vote_average: 6.3,
      vote_count: 756,
    },
    {
      adult: false,
      backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
      id: 603692,
      title: "John Wick: Chapter 4",
      original_language: "en",
      original_title: "John Wick: Chapter 4",
      overview:
        "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
      poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
      media_type: "movie" as const,
      genre_ids: [28, 53, 80],
      popularity: 1312.743,
      release_date: "2023-03-22",
      video: false,
      vote_average: 7.975,
      vote_count: 1207,
    },
    {
      adult: false,
      backdrop_path: "/pbMbDlOAkVuvnxovBA2ENin59xH.jpg",
      id: 447277,
      title: "The Little Mermaid",
      original_language: "en",
      original_title: "The Little Mermaid",
      overview:
        "The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.",
      poster_path: "/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
      media_type: "movie" as const,
      genre_ids: [12, 10751, 14, 10749],
      popularity: 210.368,
      release_date: "2023-05-18",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/rH3jY9JN9krUyE0Q3WLNtujMs8.jpg",
      id: 667538,
      title: "Transformers: Rise of the Beasts",
      original_language: "en",
      original_title: "Transformers: Rise of the Beasts",
      overview:
        "A ‘90s globetrotting adventure that introduces the Maximals, Predacons, and Terrorcons to the existing battle on earth between Autobots and Decepticons.",
      poster_path: "/g1HcrEiN0UiSpjQMJ3Klzw8KOZS.jpg",
      media_type: "movie" as const,
      genre_ids: [28, 12, 878],
      popularity: 161.222,
      release_date: "2023-06-07",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
      id: 646385,
      title: "Scream",
      original_language: "en",
      original_title: "Scream",
      overview:
        "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
      poster_path: "/4qIV5WXP1xQvpPAHmgVxCmxvPh6.jpg",
      media_type: "movie" as const,
      genre_ids: [27, 9648, 53],
      popularity: 373.035,
      release_date: "2022-01-12",
      video: false,
      vote_average: 6.737,
      vote_count: 2344,
    },
    {
      adult: false,
      backdrop_path: "/3GLrNvvkVJjBiffV8RsEh9Xg1eS.jpg",
      id: 997776,
      title: "Justice League x RWBY: Super Heroes & Huntsmen, Part One",
      original_language: "en",
      original_title:
        "Justice League x RWBY: Super Heroes & Huntsmen, Part One",
      overview:
        "Superman, Batman, Wonder Woman, Flash, Cyborg, Green Lantern and Vixen are transported to the strange world of Remnant and find themselves turned into teenagers. Meanwhile, Remnant heroes Ruby, Weiss, Blake and Yang must combine forces with the Justice League to uncover why their planet has been mysteriously altered before a superpowered Grimm destroys everything.",
      poster_path: "/sjBFnG8DpouuWi161KbjbAER235.jpg",
      media_type: "movie" as const,
      genre_ids: [16, 28, 14],
      popularity: 107.913,
      release_date: "2023-04-25",
      video: false,
      vote_average: 8.238,
      vote_count: 21,
    },
    {
      adult: false,
      backdrop_path: "/z3Qc5a0grcCREAQKqI195P05dVf.jpg",
      id: 813726,
      title: "A Tourist's Guide to Love",
      original_language: "en",
      original_title: "A Tourist's Guide to Love",
      overview:
        "After an unexpected break up, a travel executive accepts an assignment to go undercover and learn about the tourist industry in Vietnam. Along the way, she finds adventure and romance with her Vietnamese expat tour guide and they decide to hijack the tour bus in order to explore life and love off the beaten path.",
      poster_path: "/uWkpjbBe4gRZilXRXbYfsMUZMhz.jpg",
      media_type: "movie" as const,
      genre_ids: [10749, 35, 12],
      popularity: 275.635,
      release_date: "2023-04-21",
      video: false,
      vote_average: 6.603,
      vote_count: 39,
    },
    {
      adult: false,
      backdrop_path: "/vcNXzOfACCXZA7vb8SNde0LUC9o.jpg",
      id: 1068141,
      title: "Mighty Morphin Power Rangers: Once & Always",
      original_language: "en",
      original_title: "Mighty Morphin Power Rangers: Once & Always",
      overview:
        "After tragedy strikes, an unlikely young hero takes her rightful place among the Power Rangers to face off against the team's oldest archnemesis.",
      poster_path: "/vc87upO8vcAGj9OmgH3AIz6ikKB.jpg",
      media_type: "movie" as const,
      genre_ids: [28, 878, 14],
      popularity: 238.666,
      release_date: "2023-04-19",
      video: false,
      vote_average: 6.931,
      vote_count: 131,
    },
    {
      adult: false,
      backdrop_path: "/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg",
      id: 536554,
      title: "M3GAN",
      original_language: "en",
      original_title: "M3GAN",
      overview:
        "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
      poster_path: "/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
      media_type: "movie" as const,
      genre_ids: [878, 27, 35],
      popularity: 724.995,
      release_date: "2022-12-28",
      video: false,
      vote_average: 7.367,
      vote_count: 2426,
    },
    {
      adult: false,
      backdrop_path: "/xEn2SqJQ2uBAxSBfrcAqgiFDQCa.jpg",
      id: 944152,
      title: "Chokehold",
      original_language: "tr",
      original_title: "Boğa Boğa",
      overview:
        "Evading a scandal, a couple from Istanbul starts over in a town on the Aegean coast — but quickly discover the locals are determined to get rid of them.",
      poster_path: "/bW7NgAKpP24skkTjmJxNYWjOwdj.jpg",
      media_type: "movie" as const,
      genre_ids: [53, 18],
      popularity: 246.108,
      release_date: "2023-04-21",
      video: false,
      vote_average: 5.6,
      vote_count: 15,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

const tvData = {
  page: 1,
  results: [
    {
      backdrop_path: "/hP5pMJfxbY9p72LgEY6j9qGidtE.jpg",
      id: 225385,
      name: "Black Doves",
      original_name: "Black Doves",
      overview:
        "When a spy posing as a politician's wife learns her lover has been murdered, an old assassin friend joins her on a quest for truth — and vengeance.",
      poster_path: "/2eZNjPQ9f0TQDHpsL2Ecktsv5v6.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [9648, 80, 10759, 18],
      popularity: 119.346,
      first_air_date: "2024-12-05",
      vote_average: 7.1,
      vote_count: 7,
      origin_country: ["GB"],
    },
    {
      backdrop_path: "/3wfpySz5pedy6FkVID1LXXQYeYq.jpg",
      id: 202879,
      name: "Star Wars: Skeleton Crew",
      original_name: "Star Wars: Skeleton Crew",
      overview:
        "Four ordinary kids search for their home planet after getting lost in the Star Wars galaxy.",
      poster_path: "/srQbJhLRKoAwRrNN5ga7webPHbC.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [10759, 10765],
      popularity: 288.169,
      first_air_date: "2024-12-02",
      vote_average: 7.264,
      vote_count: 36,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/r2KuXtZWoq9DxFdUEWNiK8lMfRo.jpg",
      id: 219543,
      name: "Creature Commandos",
      original_name: "Creature Commandos",
      overview:
        "Follow the exploits of the Creature Commandos, a secret team of incarcerated monsters recruited for missions deemed too dangerous for humans. When all else fails…they're your last, worst option.",
      poster_path: "/bB3G6Ug1jfsOUptb0RJsqrgMVta.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [16, 10765, 10759],
      popularity: 118.059,
      first_air_date: "2024-12-05",
      vote_average: 7,
      vote_count: 1,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/bGcMuFVzW0LitMJWSzp4EjmzQ0b.jpg",
      id: 226529,
      name: "Light Shop",
      original_name: "조명가게",
      overview:
        "In a mysterious shop that sells lamps, the dead may return to the world of the living, while the living may not walk out alive.",
      poster_path: "/ykchqPqmXp2Vk2s7JMyevQGfcVM.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "ko",
      genre_ids: [9648, 18],
      popularity: 80.571,
      first_air_date: "2024-12-04",
      vote_average: 8.6,
      vote_count: 5,
      origin_country: ["KR"],
    },
    {
      backdrop_path: "/sYXLeu5usz6yEz0k00FYvtEdodD.jpg",
      id: 94605,
      name: "Arcane",
      original_name: "Arcane",
      overview:
        "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
      poster_path: "/abf8tHznhSvl9BAElD2cQeRr7do.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [16, 10765, 10759, 9648],
      popularity: 914.272,
      first_air_date: "2021-11-06",
      vote_average: 8.8,
      vote_count: 4501,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/wV6fHiVKY88GOsWkhOcXdvVUr9G.jpg",
      id: 222766,
      name: "The Day of the Jackal",
      original_name: "The Day of the Jackal",
      overview:
        "An unrivalled and highly elusive lone assassin, the Jackal, makes his living carrying out hits for the highest fee. But following his latest kill, he meets his match in a tenacious British intelligence officer who starts to track down the Jackal in a thrilling cat-and-mouse chase across Europe, leaving destruction in its wake.",
      poster_path: "/4hSnGq014MGdxCOMWBwyvKoDjrF.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [18, 10759, 9648],
      popularity: 1159.284,
      first_air_date: "2024-11-07",
      vote_average: 8.188,
      vote_count: 101,
      origin_country: ["GB"],
    },
    {
      backdrop_path: "/cud97JMlZOm3sTs0BcvqYKACTJz.jpg",
      id: 271001,
      name: "Tomorrow and I",
      original_name: "อนาฅต",
      overview:
        "This series reimagines Thailand in a dystopian future where technology scrapes at the surface of old customs, exposing rips in the fabric of culture.",
      poster_path: "/jXeqz0ul6d3CC8VKMgbGrY29vX4.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "th",
      genre_ids: [18, 10765],
      popularity: 52.375,
      first_air_date: "2024-12-04",
      vote_average: 8,
      vote_count: 3,
      origin_country: ["TH"],
    },
    {
      backdrop_path: "/11Pfh4yqjKbOgn5vY3AQD9VU4Vc.jpg",
      id: 90937,
      name: "BEASTARS",
      original_name: "BEASTARS",
      overview:
        "In a world where beasts of all kinds coexist, a gentle wolf awakens to his own predatory urges as his school deals with a murder within its midst.",
      poster_path: "/sh9iNWkleOjEHRHj8WPHhmMi8HL.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "ja",
      genre_ids: [16, 18, 9648],
      popularity: 184.737,
      first_air_date: "2019-10-10",
      vote_average: 8.5,
      vote_count: 1144,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/fn4Ah0cCWo3xSAYYiRHm4485tal.jpg",
      id: 223447,
      name: "Jentry Chau vs the Underworld",
      original_name: "Jentry Chau vs the Underworld",
      overview:
        "As her 16th birthday approaches, a not-so-average teen rediscovers the fiery powers she's long suppressed and is forced to face her demons — literally.",
      poster_path: "/2JWyp8C8eoIoagC5EWyuLXxz9tX.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [16, 10759, 10765, 35],
      popularity: 81.257,
      first_air_date: "2024-12-05",
      vote_average: 8.5,
      vote_count: 2,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/p7yp9P2K2XHqJO1ZglXJUU1mSWb.jpg",
      id: 275571,
      name: "Churchill at War",
      original_name: "Churchill at War",
      overview:
        "This captivating docuseries examines Winston Churchill's pivotal role in World War II and the formative events that made him an ideal leader for the era.",
      poster_path: "/tsgqBgTYMqTlpJZWlJK3mdZMu7I.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [99],
      popularity: 42.293,
      first_air_date: "2024-12-04",
      vote_average: 7.4,
      vote_count: 5,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg",
      id: 125988,
      name: "Silo",
      original_name: "Silo",
      overview:
        "In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts to uncover shocking secrets and the truth about the silo.",
      poster_path: "/tlliQuCupf8fpTH7RAor3aKMGy.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18],
      popularity: 1610.43,
      first_air_date: "2023-05-04",
      vote_average: 8.2,
      vote_count: 1095,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/sNSQX4Q0LYTE7UAXRFhfZP7wuLS.jpg",
      id: 73982,
      name: "Day and Night",
      original_name: "白夜追凶",
      overview:
        "Twin brothers Guan Hongfeng and Guan Hongyu find themselves caught up in a brutal massacre that destroyed their family. As they face off against a shadowy criminal organization, they join forces with others to uncover the truth behind the 213 massacre.",
      poster_path: "/uuKmigg4WuduZMJKIzJ8UP02pRg.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "zh",
      genre_ids: [80, 18, 9648],
      popularity: 669.222,
      first_air_date: "2017-08-30",
      vote_average: 8.3,
      vote_count: 39,
      origin_country: ["CN"],
    },
    {
      backdrop_path: "/pP9Or3dN8k0go1G2OSldcwBpUFO.jpg",
      id: 211039,
      name: "Senna",
      original_name: "Senna",
      overview:
        "Fascinated by cars since childhood, Brazilian racer Ayrton Senna became a sports legend — until tragedy struck, changing Formula 1 forever.",
      poster_path: "/dmRfKme3j8mbTf4iTJd0L8wtaQa.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "pt",
      genre_ids: [18],
      popularity: 279.895,
      first_air_date: "2024-11-29",
      vote_average: 8.3,
      vote_count: 41,
      origin_country: ["BR"],
    },
    {
      backdrop_path: "/o9gr7EoGPDU1IIv8Buzm2neklUM.jpg",
      id: 219971,
      name: "The Agency",
      original_name: "The Agency",
      overview:
        "Covert CIA agent Martian is ordered to abandon his undercover life and return to London Station. When the love he left behind unexpectedly reappears, their romance reignites, pitting his career, his real identity and his mission against his heart while hurling them both into a deadly game of international intrigue and espionage.",
      poster_path: "/j0fFZIksd4nu8bNLGLq8GJ4KXFA.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [18, 9648],
      popularity: 212.593,
      first_air_date: "2024-12-01",
      vote_average: 7.7,
      vote_count: 20,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/jlbUx0aHJupDVDlCo0R7UxSaUUd.jpg",
      id: 240411,
      name: "Dan Da Dan",
      original_name: "ダンダダン",
      overview:
        "In a bet to prove whether ghosts or aliens exist, two high schoolers face terrifying paranormal threats, gain superpowers and maybe even fall in love?!",
      poster_path: "/6qfZAOEUFIrbUH3JvePclx1nXzz.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "ja",
      genre_ids: [16, 10759, 35, 10765],
      popularity: 504.934,
      first_air_date: "2024-10-04",
      vote_average: 8.8,
      vote_count: 181,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/2Erj4Oav9EHAtqLI354VM7ULDqu.jpg",
      id: 73586,
      name: "Yellowstone",
      original_name: "Yellowstone",
      overview:
        "Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States. Led by their patriarch John Dutton, the family defends their property against constant attack by land developers, an Indian reservation, and America’s first National Park.",
      poster_path: "/s4QRRYc1V2e68Qy9Wel9MI8fhRP.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [37, 18],
      popularity: 1413.651,
      first_air_date: "2018-06-20",
      vote_average: 8.222,
      vote_count: 2410,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/lBoHzOgft2QfpjkVVvZCqeM4ttT.jpg",
      id: 90228,
      name: "Dune: Prophecy",
      original_name: "Dune: Prophecy",
      overview:
        "Ten thousand years before the ascension of Paul Atreides, sisters Valya and Tula Harkonnen establish the fabled sect and female order that would become known as the Bene Gesserit to control the future of humankind.",
      poster_path: "/5B8Cxz8ZZXp3w2WmmdKTXpkS24e.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18, 10759],
      popularity: 819.437,
      first_air_date: "2024-11-17",
      vote_average: 8,
      vote_count: 99,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/q3UGWifvIpdey1T2efX4dSmbZpU.jpg",
      id: 124364,
      name: "FROM",
      original_name: "FROM",
      overview:
        "Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.",
      poster_path: "/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [9648, 18, 10765],
      popularity: 1235.122,
      first_air_date: "2022-02-20",
      vote_average: 8.2,
      vote_count: 1536,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/o0NsbcIvsllg6CJX0FBFY8wWbsn.jpg",
      id: 30984,
      name: "Bleach",
      original_name: "BLEACH",
      overview:
        "For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever. Now, with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil.",
      poster_path: "/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "ja",
      genre_ids: [10759, 16, 10765],
      popularity: 710.1,
      first_air_date: "2004-10-05",
      vote_average: 8.4,
      vote_count: 1845,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
      id: 1399,
      name: "Game of Thrones",
      original_name: "Game of Thrones",
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18, 10759],
      popularity: 1348.329,
      first_air_date: "2011-04-17",
      vote_average: 8.5,
      vote_count: 24198,
      origin_country: ["US"],
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

const genreData = {
  genres: [
    {
      id: 28,
      name: "Action",
    },
    {
      id: 12,
      name: "Adventure",
    },
    {
      id: 16,
      name: "Animation",
    },
    {
      id: 35,
      name: "Comedy",
    },
    {
      id: 80,
      name: "Crime",
    },
    {
      id: 99,
      name: "Documentary",
    },
    {
      id: 18,
      name: "Drama",
    },
    {
      id: 10751,
      name: "Family",
    },
    {
      id: 14,
      name: "Fantasy",
    },
    {
      id: 36,
      name: "History",
    },
    {
      id: 27,
      name: "Horror",
    },
    {
      id: 10402,
      name: "Music",
    },
    {
      id: 9648,
      name: "Mystery",
    },
    {
      id: 10749,
      name: "Romance",
    },
    {
      id: 878,
      name: "Science Fiction",
    },
    {
      id: 10770,
      name: "TV Movie",
    },
    {
      id: 53,
      name: "Thriller",
    },
    {
      id: 10752,
      name: "War",
    },
    {
      id: 37,
      name: "Western",
    },
  ],
};

export default function Index() {
  const { results } = movieData;
  const { results: tvResults } = tvData;
  const { genres } = genreData;
  return <Home movieResults={results} tvResults={tvResults} genres={genres} />;
}
