import { useParams } from "@remix-run/react";
import { AboutPage } from "../components/pages/about";

const tvData = {
  page: 1,
  results: [
    {
      backdrop_path: "/hP5pMJfxbY9p72LgEY6j9qGidtE.jpg",
      id: 225385,
      name: "Black Doves",
      original_name: "Black Doves",
      overview:
        "When a spy posing as a politician's wife learns her lover has been murdered, an old assassin friend joins her on a quest for truth — and vengeance.",
      poster_path: "/2eZNjPQ9f0TQDHpsL2Ecktsv5v6.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [9648, 80, 10759, 18],
      popularity: 119.346,
      first_air_date: "2024-12-05",
      vote_average: 7.1,
      vote_count: 7,
      origin_country: ["GB"],
    },
    {
      backdrop_path: "/3wfpySz5pedy6FkVID1LXXQYeYq.jpg",
      id: 202879,
      name: "Star Wars: Skeleton Crew",
      original_name: "Star Wars: Skeleton Crew",
      overview:
        "Four ordinary kids search for their home planet after getting lost in the Star Wars galaxy.",
      poster_path: "/srQbJhLRKoAwRrNN5ga7webPHbC.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [10759, 10765],
      popularity: 288.169,
      first_air_date: "2024-12-02",
      vote_average: 7.264,
      vote_count: 36,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/r2KuXtZWoq9DxFdUEWNiK8lMfRo.jpg",
      id: 219543,
      name: "Creature Commandos",
      original_name: "Creature Commandos",
      overview:
        "Follow the exploits of the Creature Commandos, a secret team of incarcerated monsters recruited for missions deemed too dangerous for humans. When all else fails…they're your last, worst option.",
      poster_path: "/bB3G6Ug1jfsOUptb0RJsqrgMVta.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [16, 10765, 10759],
      popularity: 118.059,
      first_air_date: "2024-12-05",
      vote_average: 7,
      vote_count: 1,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/bGcMuFVzW0LitMJWSzp4EjmzQ0b.jpg",
      id: 226529,
      name: "Light Shop",
      original_name: "조명가게",
      overview:
        "In a mysterious shop that sells lamps, the dead may return to the world of the living, while the living may not walk out alive.",
      poster_path: "/ykchqPqmXp2Vk2s7JMyevQGfcVM.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "ko",
      genre_ids: [9648, 18],
      popularity: 80.571,
      first_air_date: "2024-12-04",
      vote_average: 8.6,
      vote_count: 5,
      origin_country: ["KR"],
    },
    {
      backdrop_path: "/sYXLeu5usz6yEz0k00FYvtEdodD.jpg",
      id: 94605,
      name: "Arcane",
      original_name: "Arcane",
      overview:
        "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
      poster_path: "/abf8tHznhSvl9BAElD2cQeRr7do.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [16, 10765, 10759, 9648],
      popularity: 914.272,
      first_air_date: "2021-11-06",
      vote_average: 8.8,
      vote_count: 4501,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/wV6fHiVKY88GOsWkhOcXdvVUr9G.jpg",
      id: 222766,
      name: "The Day of the Jackal",
      original_name: "The Day of the Jackal",
      overview:
        "An unrivalled and highly elusive lone assassin, the Jackal, makes his living carrying out hits for the highest fee. But following his latest kill, he meets his match in a tenacious British intelligence officer who starts to track down the Jackal in a thrilling cat-and-mouse chase across Europe, leaving destruction in its wake.",
      poster_path: "/4hSnGq014MGdxCOMWBwyvKoDjrF.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [18, 10759, 9648],
      popularity: 1159.284,
      first_air_date: "2024-11-07",
      vote_average: 8.188,
      vote_count: 101,
      origin_country: ["GB"],
    },
    {
      backdrop_path: "/cud97JMlZOm3sTs0BcvqYKACTJz.jpg",
      id: 271001,
      name: "Tomorrow and I",
      original_name: "อนาฅต",
      overview:
        "This series reimagines Thailand in a dystopian future where technology scrapes at the surface of old customs, exposing rips in the fabric of culture.",
      poster_path: "/jXeqz0ul6d3CC8VKMgbGrY29vX4.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "th",
      genre_ids: [18, 10765],
      popularity: 52.375,
      first_air_date: "2024-12-04",
      vote_average: 8,
      vote_count: 3,
      origin_country: ["TH"],
    },
    {
      backdrop_path: "/11Pfh4yqjKbOgn5vY3AQD9VU4Vc.jpg",
      id: 90937,
      name: "BEASTARS",
      original_name: "BEASTARS",
      overview:
        "In a world where beasts of all kinds coexist, a gentle wolf awakens to his own predatory urges as his school deals with a murder within its midst.",
      poster_path: "/sh9iNWkleOjEHRHj8WPHhmMi8HL.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "ja",
      genre_ids: [16, 18, 9648],
      popularity: 184.737,
      first_air_date: "2019-10-10",
      vote_average: 8.5,
      vote_count: 1144,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/fn4Ah0cCWo3xSAYYiRHm4485tal.jpg",
      id: 223447,
      name: "Jentry Chau vs the Underworld",
      original_name: "Jentry Chau vs the Underworld",
      overview:
        "As her 16th birthday approaches, a not-so-average teen rediscovers the fiery powers she's long suppressed and is forced to face her demons — literally.",
      poster_path: "/2JWyp8C8eoIoagC5EWyuLXxz9tX.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [16, 10759, 10765, 35],
      popularity: 81.257,
      first_air_date: "2024-12-05",
      vote_average: 8.5,
      vote_count: 2,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/p7yp9P2K2XHqJO1ZglXJUU1mSWb.jpg",
      id: 275571,
      name: "Churchill at War",
      original_name: "Churchill at War",
      overview:
        "This captivating docuseries examines Winston Churchill's pivotal role in World War II and the formative events that made him an ideal leader for the era.",
      poster_path: "/tsgqBgTYMqTlpJZWlJK3mdZMu7I.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [99],
      popularity: 42.293,
      first_air_date: "2024-12-04",
      vote_average: 7.4,
      vote_count: 5,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg",
      id: 125988,
      name: "Silo",
      original_name: "Silo",
      overview:
        "In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts to uncover shocking secrets and the truth about the silo.",
      poster_path: "/tlliQuCupf8fpTH7RAor3aKMGy.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18],
      popularity: 1610.43,
      first_air_date: "2023-05-04",
      vote_average: 8.2,
      vote_count: 1095,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/sNSQX4Q0LYTE7UAXRFhfZP7wuLS.jpg",
      id: 73982,
      name: "Day and Night",
      original_name: "白夜追凶",
      overview:
        "Twin brothers Guan Hongfeng and Guan Hongyu find themselves caught up in a brutal massacre that destroyed their family. As they face off against a shadowy criminal organization, they join forces with others to uncover the truth behind the 213 massacre.",
      poster_path: "/uuKmigg4WuduZMJKIzJ8UP02pRg.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "zh",
      genre_ids: [80, 18, 9648],
      popularity: 669.222,
      first_air_date: "2017-08-30",
      vote_average: 8.3,
      vote_count: 39,
      origin_country: ["CN"],
    },
    {
      backdrop_path: "/pP9Or3dN8k0go1G2OSldcwBpUFO.jpg",
      id: 211039,
      name: "Senna",
      original_name: "Senna",
      overview:
        "Fascinated by cars since childhood, Brazilian racer Ayrton Senna became a sports legend — until tragedy struck, changing Formula 1 forever.",
      poster_path: "/dmRfKme3j8mbTf4iTJd0L8wtaQa.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "pt",
      genre_ids: [18],
      popularity: 279.895,
      first_air_date: "2024-11-29",
      vote_average: 8.3,
      vote_count: 41,
      origin_country: ["BR"],
    },
    {
      backdrop_path: "/o9gr7EoGPDU1IIv8Buzm2neklUM.jpg",
      id: 219971,
      name: "The Agency",
      original_name: "The Agency",
      overview:
        "Covert CIA agent Martian is ordered to abandon his undercover life and return to London Station. When the love he left behind unexpectedly reappears, their romance reignites, pitting his career, his real identity and his mission against his heart while hurling them both into a deadly game of international intrigue and espionage.",
      poster_path: "/j0fFZIksd4nu8bNLGLq8GJ4KXFA.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [18, 9648],
      popularity: 212.593,
      first_air_date: "2024-12-01",
      vote_average: 7.7,
      vote_count: 20,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/jlbUx0aHJupDVDlCo0R7UxSaUUd.jpg",
      id: 240411,
      name: "Dan Da Dan",
      original_name: "ダンダダン",
      overview:
        "In a bet to prove whether ghosts or aliens exist, two high schoolers face terrifying paranormal threats, gain superpowers and maybe even fall in love?!",
      poster_path: "/6qfZAOEUFIrbUH3JvePclx1nXzz.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "ja",
      genre_ids: [16, 10759, 35, 10765],
      popularity: 504.934,
      first_air_date: "2024-10-04",
      vote_average: 8.8,
      vote_count: 181,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/2Erj4Oav9EHAtqLI354VM7ULDqu.jpg",
      id: 73586,
      name: "Yellowstone",
      original_name: "Yellowstone",
      overview:
        "Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States. Led by their patriarch John Dutton, the family defends their property against constant attack by land developers, an Indian reservation, and America’s first National Park.",
      poster_path: "/s4QRRYc1V2e68Qy9Wel9MI8fhRP.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [37, 18],
      popularity: 1413.651,
      first_air_date: "2018-06-20",
      vote_average: 8.222,
      vote_count: 2410,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/lBoHzOgft2QfpjkVVvZCqeM4ttT.jpg",
      id: 90228,
      name: "Dune: Prophecy",
      original_name: "Dune: Prophecy",
      overview:
        "Ten thousand years before the ascension of Paul Atreides, sisters Valya and Tula Harkonnen establish the fabled sect and female order that would become known as the Bene Gesserit to control the future of humankind.",
      poster_path: "/5B8Cxz8ZZXp3w2WmmdKTXpkS24e.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18, 10759],
      popularity: 819.437,
      first_air_date: "2024-11-17",
      vote_average: 8,
      vote_count: 99,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/q3UGWifvIpdey1T2efX4dSmbZpU.jpg",
      id: 124364,
      name: "FROM",
      original_name: "FROM",
      overview:
        "Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.",
      poster_path: "/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [9648, 18, 10765],
      popularity: 1235.122,
      first_air_date: "2022-02-20",
      vote_average: 8.2,
      vote_count: 1536,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/o0NsbcIvsllg6CJX0FBFY8wWbsn.jpg",
      id: 30984,
      name: "Bleach",
      original_name: "BLEACH",
      overview:
        "For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever. Now, with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil.",
      poster_path: "/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "ja",
      genre_ids: [10759, 16, 10765],
      popularity: 710.1,
      first_air_date: "2004-10-05",
      vote_average: 8.4,
      vote_count: 1845,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
      id: 1399,
      name: "Game of Thrones",
      original_name: "Game of Thrones",
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      media_type: "tv" as const,
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18, 10759],
      popularity: 1348.329,
      first_air_date: "2011-04-17",
      vote_average: 8.5,
      vote_count: 24198,
      origin_country: ["US"],
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

const TvDetail = () => {
  const { id } = useParams();
  const tv = tvData.results.find((tv) => tv.id === Number(id));

  return <AboutPage data={tv} />;
};

export default TvDetail;
